- name: Elasticsearch add data node
  hosts: Elasticsearch-3
  remote_user: ec2-user
  roles:
    #expand to all available parameters
    - { role: node,
        es_instance_name: "node-3",
        es_config: {
          node.name: "node-3", 
          cluster.name: "cluster-es",
          network.host: {node-4 ip},
          http.port: 9203,
          http.enabled: true,
          transport.tcp.port: 9303,
          discovery.zen.ping.unicast.hosts: "{node-0 ip}:9300,{node-1 ip}:9301,{node-2 ip}:9302,{{node-3 ip}}:9303",
          discovery.zen.minimum_master_nodes: 2,
          node.data: true, 
          node.master: false,
          node.ingest: false
        }
      }
  vars:
    es_scripts: false
    es_templates: false
    es_heap_size: 512m
    es_start_service: true
    es_plugins_reinstall: false

- name: Metricbeat install
  hosts: Elasticsearch-4
  remote_user: ec2-user
  roles:
    #expand to all available parameters
    - { role: metricbeat,
        instance_name: "node-3",
        metricbeat_hosts: "{node-0 ip}:9200\", \"{node-2 ip}:9201\", \"{node-2 ip}:9202\", \"{node-3 ip}:9203",
        kibana_host: "{kibana ip}"
      }
