- name: Elasticsearch single node
  hosts: Elasticsearch-0
  remote_user: ec2-user
  roles:
    - { role: node,
        es_instance_name: "node-0",
        es_config: {
          node.name: "node-0", 
          cluster.name: "cluster-es",
          network.host: {node-0 private ip},
          http.port: 9200,
          http.enabled: true,
          transport.tcp.port: 9300,
          discovery.zen.ping.unicast.hosts: "{node-0 private ip}:9300,{node-1 private ip}:9301,{node-2 private ip}:9302",
          discovery.zen.minimum_master_nodes: 2,
          node.data: true, 
          node.master: true,
          node.ingest: false
        }
      }
  vars:
    es_scripts: false
    es_templates: false
    es_heap_size: 512m
    es_start_service: true
    es_plugins_reinstall: false

- name: Elasticsearch single node
  hosts: Elasticsearch-1
  remote_user: ec2-user
  roles:
    - { role: node,
        es_instance_name: "node-1",
        es_config: {
          node.name: "node-1",
          cluster.name: "cluster-es",
          network.host: {node-1 private ip},
          http.port: 9201,
          http.enabled: true,
          transport.tcp.port: 9301,
          discovery.zen.ping.unicast.hosts: "{node-0 private ip}:9300,{node-1 private ip}:9301,{node-2 private ip}:9302",
          discovery.zen.minimum_master_nodes: 2,
          node.data: true, 
          node.master: true,
          node.ingest: false
        }
      }
  vars:
    es_scripts: false
    es_templates: false
    es_heap_size: 512m
    es_start_service: true
    es_plugins_reinstall: false

- name: Elasticsearch single node
  hosts: Elasticsearch-2
  remote_user: ec2-user
  roles:
    - { role: node,
        es_instance_name: "node-2",
        es_config: {
          node.name: "node-2", 
          cluster.name: "cluster-es",
          network.host: {node-2 private ip},
          http.port: 9202,
          http.enabled: true,
          transport.tcp.port: 9302,
          discovery.zen.ping.unicast.hosts: "{node-0 private ip}:9300,{node-1 private ip}:9301,{node-2 private ip}:9302",
          discovery.zen.minimum_master_nodes: 2,
          node.data: true, 
          node.master: true,
          node.ingest: false
        }
      }
  vars:
    es_scripts: false
    es_templates: false
    es_heap_size: 512m
    es_start_service: true
    es_plugins_reinstall: false

