- name: Metricbeat install
  hosts: Elasticsearch-0
  remote_user: ec2-user
  roles:
    - { role: metricbeat,
        instance_name: "node-0",
        metricbeat_hosts: "{node-0 private ip}:9200\", \"{node-1 private ip}:9201\", \"{node-2 private ip}:9202",
        kibana_host: "{kibana ip}:5601"
      }

- name: Metricbeat install
  hosts: Elasticsearch-1
  remote_user: ec2-user
  roles:
    - { role: metricbeat,
        instance_name: "node-1",
        metricbeat_hosts: "{node-0 private ip}:9200\", \"{node-1 private ip}:9201\", \"{node-2 private ip}:9202",
        kibana_host: "{kibana ip}:5601"
      }

- name: Metricbeat install
  hosts: Elasticsearch-2
  remote_user: ec2-user
  roles:
    - { role: metricbeat,
        instance_name: "node-2",
        metricbeat_hosts: "{node-0 private ip}:9200\", \"{node-1 private ip}:9201\", \"{node-2 private ip}:9202",
        kibana_host: "{kibana ip}:5601"
      }
