
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled
- name: restart metricbeat
  become: yes
  service: name=metricbeat state=restarted enabled=yes
