---
- name: check-set-parameters and setting init variable
  include: elasticsearch-parameters.yml
  tags:
      - always

- include: java.yml
  when: es_java_install
  tags:
      - java

- include: elasticsearch.yml
  tags:
      - install

- include: elasticsearch-config.yml
  tags:
      - config

- meta: flush_handlers

- name: Make sure elasticsearch is started
  become: yes
  service: name=elasticsearch state=started enabled=yes
  when: es_start_service
  delay: 10

# - name: Wait for elasticsearch to startup
#   wait_for: host={{es_api_host}} port={{es_api_port}} delay=5 connect_timeout=1
#   when: es_restarted is defined and es_restarted.changed and es_start_service

#Templates done after restart - handled by flushing the handlers. e.g. suppose user removes security on a running node and doesn't specify es_api_basic_auth_username and es_api_basic_auth_password.  The templates will subsequently not be removed if we don't wait for the node to restart.
#We also do after the native realm to ensure any changes are applied here first and its denf up.
# - include: elasticsearch-template.yml
#   when: es_templates
#   tags:
#       - templates