---

# elasticsearch repo 설정 - metricbeat 설치 목적
- name: Add Elasticsearch repo
  become: yes
  template: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch-{{ es_major_version }}.repo

# metricbeat install
- name: Install Metricbeat
  become: yes
  yum: name=metricbeat state=installed update_cache=yes
  notify: restart metricbeat
  delay: 10

